[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$sourcePath = Join-Path $repositoryRoot 'Development Guidelines.md'
$targetPaths = @(
    (Join-Path $repositoryRoot 'AGENTS.md'),
    (Join-Path $repositoryRoot 'CLAUDE.md')
)

if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
    Write-Error "Source file is missing: $sourcePath"
    exit 1
}

$warning = @'
<!--
GENERATED FILE

This file is generated from Development Guidelines.md.
Do not edit this file directly.

After changing Development Guidelines.md, run:
./scripts/sync-agent-instructions.ps1
-->
'@

$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
$sourceContent = [System.IO.File]::ReadAllText($sourcePath)
$expectedContent = ($warning + "`n`n" + $sourceContent) -replace "`r?`n", "`r`n"
$expectedBytes = $utf8WithoutBom.GetBytes($expectedContent)

if ($Check) {
    $hasDifference = $false

    foreach ($targetPath in $targetPaths) {
        if (-not (Test-Path -LiteralPath $targetPath -PathType Leaf)) {
            Write-Error "Generated file is missing: $targetPath" -ErrorAction Continue
            $hasDifference = $true
            continue
        }

        $actualBytes = [System.IO.File]::ReadAllBytes($targetPath)
        $actualBase64 = [System.Convert]::ToBase64String($actualBytes)
        $expectedBase64 = [System.Convert]::ToBase64String($expectedBytes)
        if ($actualBase64 -cne $expectedBase64) {
            Write-Error "Generated file is out of sync: $targetPath" -ErrorAction Continue
            $hasDifference = $true
        }
        else {
            Write-Host "In sync: $targetPath"
        }
    }

    if ($hasDifference) {
        Write-Error 'Agent instruction files are not synchronized. Run ./scripts/sync-agent-instructions.ps1.'
        exit 1
    }

    Write-Host 'Agent instruction files are synchronized.'
    exit 0
}

foreach ($targetPath in $targetPaths) {
    [System.IO.File]::WriteAllBytes($targetPath, $expectedBytes)
    Write-Host "Updated: $targetPath"
}
